#############################################################################################################################
# Master script to render final HTML file from R Markdown file
# Loads all required packages from the dependencies folder
#
# Make sure the 'plyr' is not loaded after 'dplyr' library in the same R session
# Under such case, the group_by features of dplyr library does not work. Restart RStudio and make sure
# plyr library is not loaded while generating dashboard
# For more info on this issue: 
# https://stackoverflow.com/questions/26923862/why-are-my-dplyr-group-by-summarize-not-working-properly-name-collision-with
#
#############################################################################################################################

##### LIST OF ALL INPUT FILES #####
## 0. Path input data                   : parameters.csv
## 1. Base scenario summary file names  : summaryFilesNames_survey.csv
## 2. Build scenario summary file names : summaryFilesNames.csv
## 3. Model area shapefile              : summaryFilesNames.csv
## 4. All REF and ABM summary output files

library(data.table)
library(yaml)


### Read Command Line Arguments
#args                <- commandArgs(trailingOnly = TRUE)
#Parameters_File     <- args[1]
showWarnings=FALSE
rm(list=ls())

### Read parameters from Parameters_File
setwd('C:/gitclones/Dubai_survey_processing')
parameters       = read_yaml(file.path(getwd(), "configs/visualizer_specs/parameters.yaml"))

### Read code book values
# codebook_file = file.path(getwd(), 'configs/visualizer_specs/visualizer_codebook.csv')
# codebook = fread(codebook_file)
# codebook_list = split(codebook, codebook$var)
# names(codebook_list) = paste0(names(codebook_list), '_df')
codebook_list = read_yaml(file.path(getwd(), 'configs/constants.yaml'))

### Combine parameters and codebook, convert list of list to name vector
all_parameters = c(parameters, codebook_list)

all_parameters = lapply(all_parameters, function(var) {
  if(class(var)[1]=='list') {
      unlist(var)
    } else {
      var
    }
  })

### Send vars to environment
for (var_name in names(all_parameters)) {
  assign(var_name, all_parameters[[var_name]])
}



### Paths
SYSTEM_APP_PATH = file.path(getwd(), 'framework/modules/visualizer')
TEMPLATE_PATH = file.path(SYSTEM_APP_PATH, 'template.Rmd')

### Names
if(IS_BASE_SURVEY=="Yes"){
  #   Surey Base
  BASE_SCENARIO_ALT     <- "IBI"
  DISTRICT_FLOW_CENSUS  <- "IBI"
  AO_CENSUS_SHORT       <- "IBI"
  AO_CENSUS_LONG        <- "IBI"
}else{
  #   Non-Survey Base
  BASE_SCENARIO_ALT     <- BASE_SCENARIO_NAME
  DISTRICT_FLOW_CENSUS  <- BASE_SCENARIO_NAME
  AO_CENSUS_SHORT       <- BASE_SCENARIO_NAME
  AO_CENSUS_LONG        <- BASE_SCENARIO_NAME
}


### Initialization
# Load global variables
#.libPaths(R_LIBRARY)

# If not specified in codebook, it can be autogenerated from increment

if(N_TIME_PERIODS == 40) {
todBins               <- c("03:00 AM to 05:00 AM","05:00 AM to 05:30 AM","05:30 AM to 06:00 AM","06:00 AM to 06:30 AM","06:30 AM to 07:00 AM",
                           "07:00 AM to 07:30 AM","07:30 AM to 08:00 AM","08:00 AM to 08:30 AM", "08:30 AM to 09:00 AM","09:00 AM to 09:30 AM",
                           "09:30 AM to 10:00 AM","10:00 AM to 10:30 AM", "10:30 AM to 11:00 AM","11:00 AM to 11:30 AM", "11:30 AM to 12:00 PM",
                           "12:00 PM to 12:30 PM", "12:30 PM to 01:00 PM","01:00 PM to 01:30 PM", "01:30 PM to 02:00 PM","02:00 PM to 02:30 PM",
                           "02:30 PM to 03:00 PM","03:00 PM to 03:30 PM", "03:30 PM to 04:00 PM","04:00 PM to 04:30 PM", "04:30 PM to 05:00 PM",
                           "05:00 PM to 05:30 PM", "05:30 PM to 06:00 PM","06:00 PM to 06:30 PM", "06:30 PM to 07:00 PM","07:00 PM to 07:30 PM",
                           "07:30 PM to 08:00 PM","08:00 PM to 08:30 PM", "08:30 PM to 09:00 PM","09:00 PM to 09:30 PM", "09:30 PM to 10:00 PM",
                           "10:00 PM to 10:30 PM", "10:30 PM to 11:00 PM","11:00 PM to 11:30 PM", "11:30 PM to 12:00 AM","12:00 AM to 03:00 AM")


durBins               <- c("(0.5 hours)","(1 hours)","(1.5 hours)","(2 hours)","(2.5 hours)","(3 hours)","(3.5 hours)","(4 hours)","(4.5 hours)",
                           "(5 hours)","(5.5 hours)","(6 hours)","(6.5 hours)","(7 hours)","(7.5 hours)","(8 hours)","(8.5 hours)","(9 hours)",
                           "(9.5 hours)","(10 hours)","(10.5 hours)","(11 hours)","(11.5 hours)","(12 hours)","(12.5 hours)","(13 hours)",
                           "(13.5 hours)","(14 hours)","(14.5 hours)","(15 hours)","(15.5 hours)","(16 hours)","(16.5 hours)","(17 hours)",
                           "(17.5 hours)","(18 hours)","(18.5 hours)","(19 hours)","(19.5 hours)","(20 hours)")

} else{
  tod_seq = seq(0, 24, 24/N_TIME_PERIODS)
  time = paste(sprintf("%02d", tod_seq %/% 1), sprintf("%02d", 60 * tod_seq %% 1))
  todBins = sapply(1:(length(time)-1), function(i) paste(time[i], 'to', time[i+1]))
}

tod_df = data.frame(var='tod', 
                    code = seq(from=1, to=N_TIME_PERIODS), name = todBins)

dur_df = data.frame(var='duration',
                    code = seq(from=1, to=nrow(tod_df)),
                    name = paste0('(', seq(0.5, nrow(tod_df)/2, 0.5), ' hours)'))

outDirDist = sapply(seq(0, N_TIME_PERIODS-1), function(i) paste0(i, '-', i+1))


# Dumb vector labels
vec2df <- function(v, rev=FALSE) {
  if(rev) {
    data.frame(name = v, code = names(v)) 
  } else {
    data.frame(name = names(v), code = v) 
  }
}


dap_types = DAP_TYPES

timePeriods = names(TIME_PERIODS)
timePeriodBreaks = c(0, TIME_PERIODS)

durBins = dur_df$name
jtf_alternatives = names(JTF_ALTS)
tourMode = names(TOUR_MODE)
tripMode = names(TRIP_MODE)

purpose_type_df = vec2df(TOUR_PURPOSE, TRUE)
purpose_type_df = rbind(purpose_type_df, data.frame(name='Total', code='Total'))


stopPurposes = names(PURPOSE)
person_type_char = names(PERTYPE)

person_type_df = vec2df(PERTYPE, FALSE)
person_type_df = rbind(person_type_df, data.frame(name='Total', code='Total'))


mtf_df = vec2df(MTF)
mtf_names = names(MTF)


### Load required libraries
SYSTEM_REPORT_PKGS <- c("DT", "flexdashboard", "leaflet", "geojsonio",
                        "htmltools", "htmlwidgets", "kableExtra",
                        "knitr", "mapview", "plotly", "RColorBrewer",
                        "rgdal", "rgeos", "crosstalk","treemap", "htmlTable",
                        "rmarkdown", "scales", "stringr", "jsonlite",
                        "pander", "ggplot2", "reshape", "raster", "dplyr")

lapply(SYSTEM_REPORT_PKGS, library, character.only = TRUE)

### Read Target and Output Summary files
# Base data
base_data <- lapply(list.files(VIS_BASE_DATA_DIR, full.names = TRUE), fread)
base_csv_names <- gsub('.csv','', list.files(VIS_BASE_DATA_DIR))
names(base_data) <- base_csv_names

# Build data
build_data <- lapply(list.files(VIS_BUILD_DATA_DIR, full.names = TRUE), fread)
build_csv_names <- gsub('.csv','', list.files(VIS_BUILD_DATA_DIR))
names(build_data) <- build_csv_names



### Generate dashboard
rmarkdown::render(TEMPLATE_PATH, output_dir = VIS_DIR,
                  intermediates_dir = VIS_DIR, quiet = TRUE)



template.html <- readLines(file.path(VIS_DIR, "template.html"))
idx <- which(template.html == "window.FlexDashboardComponents = [];")[1]
template.html <- append(template.html, "L_PREFER_CANVAS = true;", after = idx)
writeLines(template.html, file.path(VIS_DIR, paste(OUTPUT_HTML_NAME, ".html", sep = "")))
file.remove(file.path(VIS_DIR, "template.html"))

# finish