# The following are for handling awkward hard-coded mappings in the SPA tool.
# TODO: Future improvements should be made at streamlining this.


# CONSTANTS
# IN_DIR: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/new/"
# OUT_DIR_PATH: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/output/"
COMPUTE_TRIP_DIST: True     #true if trip distance is to be computed from route file
NEGLIGIBLE_DELTA_TIME: 10   #time stamps within this margin of difference can be considered as identical 
MAX_VOLUNTEER_MINUTES: 120  #work duration le this value is considered volunteer work 
MAX_XFERS: 3                #number of place holders for transit transfers in the output trip file
START_OF_DAY_MIN: 180       #3:00am
TIME_WINDOW_BIN_MIN: 30     #bin width in minutes
WORK_LOCATION_BUFFER: 0.25  # distance buffer to check if activity location is primary work location
INDEX_JTRIP_BY_DEPTIME: 0   #1 if index by trip departure time at origin, 0 if by trip arrival time at destination
SurveyChangeModeCode: 7
SurveyHomeCode: [1,2]
SURVEY_DO_PURP_CODE: 8
SURVEY_PU_PURP_CODE: 9
SurveySchoolPurp: [5,6]
SurveyWorkPurp: [3,4]
SurveyWorkRelatedPurp: 11


# map TPURP from OHAS to the corresponding PURP code
# TODO: This seems weird, can it be removed?
# SurveyTpurp2Purp:
    # 1: 0
    # 2: 0
    # 3: 1
    # 4: 1
    # 5: 2
    # 6: 3
    # 7: 12 #should not be "Change Mode" unless this is a partial-tour
    # 8: 4
    # 9: 4
    # 10: 13
    # 11: 10
    # 12: 6
    # 13: 5
    # 14: 5
    # 15: 6
    # 16: 6
    # 17: 7
    # 18: 6
    # 19: 9
    # 20: 9
    # 21: 9
    # 22: 8
    # 96: 11
    # 97: 13
    # 99: 13
    # -9998: 13

# map Survey mode name to mode code
SurveyMode:
    'SOV-FREE': 1
    'SOV-PAY':  2
    'HOV2-FREE':  3
    'HOV2-PAY': 4
    'HOV3-FREE': 5
    'HOV3-PAY': 6
    'WALK': 7
    'BIKE': 8
    'WALK-LB': 9
    'WALK-EB': 10
    'WALK-LR': 11
    'WALK-CR': 12
    'PNR-LB': 13
    'PNR-EB': 14
    'PNR-LR': 15
    'PNR-CR': 16
    'KNR-LB': 17
    'KNR-EB': 18
    'KNR-LR': 19
    'KNR-CR': 20
    'SCHOOLBUS': 21
    'TAXI': 22
    'OTHER': 23

# survey definition for driver/passanger
SurveyDriver:
    'DRIVER': 1
    'PASSENGER': 2
    'NA': 0

# Survey definition for toll payment
SurveyToll:
    'TOLL': 0
    'NOTOLL': 1

SurveyTbus2TransitType:
    1: 'BUS'
    2: 'LRT'
    3: 'BRT'
    default: 'BUS'


# Updated to represent agg modes in SANDAG survey
NewTripMode:
    'SOV-FREE': 1
    'SOV-PAY': 2
    'HOV2-FREE': 3
    'HOV2-PAY': 4
    'HOV3-FREE': 5
    'HOV3-PAY': 6
    'WALK': 7
    'BIKE': 8
    'WALK-LB': 9
    'WALK-EB': 10
    'WALK-LR': 11
    'WALK-CR': 12
    'PNR-LB': 13
    'PNR-EB': 14
    'PNR-LR': 15
    'PNR-CR': 16
    'KNR-LB': 17
    'KNR-EB': 18
    'KNR-LR': 19
    'KNR-CR': 20
    'SCHOOLBUS': 21
    'TAXI': 22
    'OTHER': 23

NewTransitAccess:
    'PNR':  1
    'KNR':  2
    'WALK': 3

# map new mode name to mode code
NewTourMode:
    'SOV':      1
    'HOV2':     2
    'HOV3':     3
    'WALK':     4
    'BIKE':     5
    'WT':       6
    'PNR':      7
    'KNR':      8
    'SCHOOLBUS': 9
    'TAXI':     10
    'OTHER':    11

# Map new purpose name to purpose code
NewPurp:
    'HOME':          0
    'WORK':          1
    'UNIVERSITY':    2
    'SCHOOL':        3
    'ESCORTING':     4
    'SHOPPING':      5
    'MAINTENANCE':   6
    'EAT OUT':       7
    'SOCIAL/VISIT':  8
    'DISCRETIONARY': 9
    'WORK-RELATED':  10
    'LOOP':          11
    'CHANGE MODE':   12
    'OTHER':         13

# Map partial tour types to numeric code
NewPartialTour:
    'NOT_PARTIAL':      0  #not a partial tour
    'PARTIAL_START':    1  #first tour of the day not starting at home
    'PARTIAL_END':      2   #last tour of the day not ending at home

NewEscort:
    'NEITHER':  0  #neither pick up or drop off
    'PICK_UP':  1  #pick up passenger
    'DROP_OFF': 2   #drop off passenger
    'PICK_UP_NON_HH':     3   #pick up non household member
    'DROP_OFF_NON_HH':    4   #pick up non household member
    'BOTH_PUDO':          5

NewEscortType:
    'RIDE_SHARING': 1
    'PURE_ESCORT': 2
    'NO_ESCORT': 3

NewPerType:
    'FW' : 1
    'PW' : 2
    'US' : 3
    'NW' : 4
    'RE' : 5
    'DS' : 6
    'ND' : 7
    'PS' : 8

NewStuCategory:
    'SCHOOL':       1
    'UNIVERSITY':   2
    'NON-STUDENT':  3

NewEmpCategory:
    'FULLTIME':     1
    'PARTTIME':     2
    'UNEMPLOYED':   3
    'NON-WORKER':   4

# Map travel party composition label to code
NewCompType:
    'ALL_ADULTS':    1
    'ALL_CHILDREN':  2
    'MIXED':         3

NewJointCategory:
    'NOT-JOINT':     0
    'JOINT':         1
    'JOINT-GROUPED': 2

NewJointTourStatus:
    'INDEPENDENT':   1
    'PART_JOINT':    2
    'FULL_JOINT':    3
    'PROB_JOINT':    4
