# The following are for handling awkward hard-coded mappings in the SPA tool.
# TODO: Future improvements should be made at streamlining this.


# CONSTANTS
# IN_DIR: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/new/"
# OUT_DIR_PATH: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/output/"
COMPUTE_TRIP_DIST: True     #true if trip distance is to be computed from route file
NEGLIGIBLE_DELTA_TIME: 10   #time stamps within this margin of difference can be considered as identical 
MAX_VOLUNTEER_MINUTES: 120  #work duration le this value is considered volunteer work 
MAX_XFERS: 3                #number of place holders for transit transfers in the output trip file
START_OF_DAY_MIN: 180       #3:00am
TIME_WINDOW_BIN_MIN: 30     #bin width in minutes
WORK_LOCATION_BUFFER: 0.25  # distance buffer to check if activity location is primary work location
INDEX_JTRIP_BY_DEPTIME: 0   #1 if index by trip departure time at origin, 0 if by trip arrival time at destination
CHANGE_MODE_CODE: 12
HOME_CODE: 0
SURVEY_DO_PURP_CODE: 8
SURVEY_PU_PURP_CODE: 9
SCHOOL_PURP: 2
UNIV_PURP: 3
WORK_PURP: 1
WORK_RELATED_PURP: 10


N_TIME_PERIODS: 48
TIME_PERIODS: # 48 periods, with period 1 starting at 3am, 
    Early-AM:           8   # 03:00-07:00
    AM-Peak:            12  # 07:00-09:00
    Midday-Pre-Lunch:   20  # 09:00-13:00    
    Midday-Lunch:       24  # 13:00-15:00
    Midday-Post-Lunch:  28  # 15:00-17:00
    PM-Peak:            34  # 17:00-20:00
    Evening:            49  # 20:00-03:00 *Next day

DAP_TYPES: ["M", "N", "H"]


# map mode name to mode code
TRIPMODE:
    'SOV': 1
    'HOV2':  2
    'HOV3+': 3
    'WALK': 4
    'BIKE': 5
    'TNC / TAXI': 6
    'WALK-BUS': 7    
    'WALK-METRO': 8
    'PNR-BUS': 9
    'PNR-METRO': 10
    'KNR-BUS': 11
    'KNR-METRO': 12
    'COMPANY-BUS': 13
    'SCHOOLBUS': 14
    'OTHER': 15

# Map trip modes to tour modes
# use list to aggregate multiple (e.g., pnr-bus pnr-metro -> pnr)
TOURMODE:
    'SOV': 1
    'HOV2':  2
    'HOV3+': 3
    'WALK': 4
    'BIKE': 5
    'TNC / TAXI': 6
    'WALK-BUS': 7    
    'WALK-METRO': 8
    'PNR-BUS': 9
    'PNR-METRO': 10
    'KNR-BUS': 11
    'KNR-METRO': 12
    'COMPANY-BUS': 13
    'SCHOOLBUS': 14
    'OTHER': 15

# survey definition for driver/passanger
DRIVER:
    'DRIVER': 1
    'PASSENGER': 2
    'NA': 0

# Survey definition for toll payment
TOLL:
    'TOLL': 1
    'NOTOLL': 2
    
TRANSIT_MODES: [7, 8, 9, 10, 11, 12]

TRANSIT_TYPES:
    'BUS': 1
    'LRT': 2
    'BRT': 3
    'default': 'BUS'

TRANSIT_ACCESS:
    'PNR':  1
    'KNR':  2
    'WALK': 3

# Map new purpose name to purpose code
PURPOSE:
    'HOME':          0
    'WORK':          1
    'UNIVERSITY':    2
    'SCHOOL':        3
    'ESCORTING':     4
    'SHOPPING':      5
    'MAINTENANCE':   6
    'EAT OUT':       7
    'SOCIAL/VISIT':  8
    'DISCRETIONARY': 9
    'WORK-RELATED':  10
    'LOOP':          11
    'CHANGE MODE':   12
    'OTHER':         13
    
#TODO convert to integers?
# TOURPURP:
    # 'atwork': 1 # 'At-Work'
    # 'esc': 2    # 'Escorting'
    # 'esco': 3   # 'Escorting'
    # 'idisc': 4  # 'Indi-Discretionary'
    # 'imain': 5  # 'Indi-Maintenance'
    # 'jdisc': 6  # 'Joint-Discretionary'
    # 'jmain': 7  # 'Joint-Maintenance'
    # 'sch': 8    # 'School'
    # 'schl': 9   # 'School'
    # 'univ': 10  # 'University'
    # 'work': 11  # 'Work'
    
    
# Purpose grouping
STOP_PURPOSES:
    # FULLY_JOINT == 0
    INDIV:
        'WORK':        1
        'UNIVERSITY':  2
        'SCHOOL':      3
        'ESCORTING':   4
        'INDIV-MAINT': [5, 6]
        'INDIV-DISC':  [7, 8, 9]
    # FULLY_JOINT == 1
    JOINT:
        'JOINT-MAINT': [5, 6]
        'JOINT-DISC':  [7, 8, 9]
    # IS_SUBTOUR == 1
    SUBTOUR:
        'WORK-RELATED':  10
    
    
JTF_ALTS:
    'No Joint Tours': 1
     # Codes for JOINT_PURP_x == 1
    '1 Shopping': 2
    '1 Maintenance': 3
    '1 Eating Out': 4
    '1 Visiting': 5
    '1 Other Discretionary': 6    
    # Codes for JOINT_PURP_x > 1 
    '2 Shopping': 7   
    '1 Shopping / 1 Maintenance': 8
    '1 Shopping / 1 Eating Out': 9
    '1 Shopping / 1 Visiting': 10
    '1 Shopping / 1 Other Discretionary': 11
    # Codes for JOINT_PURP_x > 1 and JOINT_PURP_y > 1 where x < y
    '2 Maintenance': 12                             # [5,6]
    '1 Maintenance / 1 Eating Out': 13              # [5,7]
    '1 Maintenance / 1 Visiting': 14                # [5,8]
    '1 Maintenance / 1 Other Discretionary': 15     # [5,9]
    '2 Eating Out': 16                              # [6,7]
    '1 Eating Out / 1 Visiting': 17                 # [6,8]
    '1 Eating Out / 1 Other Discretionary': 18      # [6,9]
    '2 Visiting': 19                                # [7,8]
    '1 Visiting / 1 Other Discretionary': 20        # [7,9]
    '2 Other Discretionary': 21                     # [8,9]
 

# Map partial tour types to numeric code
PARTIAL_TOUR:
    'NOT_PARTIAL':      0  #not a partial tour
    'PARTIAL_START':    1  #first tour of the day not starting at home
    'PARTIAL_END':      2   #last tour of the day not ending at home

ESCORT_EVENT:
    'NEITHER':  0  #neither pick up or drop off
    'PICK_UP':  1  #pick up passenger
    'DROP_OFF': 2   #drop off passenger
    'PICK_UP_NON_HH':     3   #pick up non household member
    'DROP_OFF_NON_HH':    4   #pick up non household member
    'BOTH_PUDO':          5

ESCORT_TYPE:
    'RIDE_SHARING': 1
    'PURE_ESCORT': 2
    'NO_ESCORT': 3

PERSONTYPE:
    'Full-time Emirati worker': 1
    'Full-time non-Emirati worker': 2
    'Labourer': 3
    'Part-time Emirati worker': 4
    'Part-time non-Emirati worker': 5
    'University Student': 6
    'Non-worker and non-student': 7
    'Non-working senior': 8
    'K-12 Emirati Student': 9
    'K-12 non-Emirati Student': 10
    'Pre-school': 11

MAND_PERSONTYPES: [1, 2, 3, 6, 8, 9, 10, 11]
UNIV_TYPES: 6    
K12_TYPES: [9, 10]
PRESCHOOL_TYPES: 11
PARTTIME_TYPES: [4, 5]
NONWORKER_TYPES: [7, 8]
EMIRATI_TYPES: [1, 3, 4, 6, 7, 8, 9, 11]
NONEMIRATI_TYPES: [2, 3, 5, 6, 7, 8, 10, 11]

PERSONTYPE_SURVEY:
    "None": 0
    Local_male: 1           #Local_male
    Local_female: 2           #Local_female
    Exp_m_HI: 3           #Expatriate_male_High income
    Exp_m_CA_MI: 4           #Expatriate_male_Car available_Medium income
    Exp_m_CA_LI: 5           #Expatriate_male_Car available_Low income
    Exp_m_NCA_MI: 6           #Expatriate_male_No car available_Medium income
    Exp_m_NCA_LI: 7           #Expatriate_male_No car available_Low income
    Exp_f_HI: 8           #Expatriate_female_High income
    Exp_f_CA_MI: 9           #Expatriate_female_Car available_Medium income
    Exp_f_CA_LI: 10           #Expatriate_female_Car available_Low income
    Exp_f_NCA_MI: 11           #Expatriate_female_No car available_Medium income
    Exp_f_NCA_LI: 12           #Expatriate_female_No car available_Low income
    Local_P1: 13           #Local Pupil 1 (Primary School)
    Local_P2: 14           #Local Pupil 2 (Secondary School)
    Expat_P1: 15           #Expatriate Pupil 1 (Primary School)
    Expat_P2: 16           #Expatriate Pupil 2 (Secondary School)
    Students: 17           #Student
    Retired: 18           #Retired Person
    LabC_CA: 19           #Labourer  (Construction)_Car available
    LabC_NCA: 20           #Labourer  (Construction)_No car available
    LabO_CA: 21           #Labourer  (others)_Car available
    LabO_NCA: 22           #Labourer  (others)_No car available
    Visitors_Tourists: 23           #(Not covered in HIS)
    Visitors_Business: 24           #(Not covered in HIS)

    

STUDENT:
    'SCHOOL':       1
    'UNIVERSITY':   2
    'NON-STUDENT':  3

EMPLOYMENT:
    'FULLTIME':     1
    'PARTTIME':     2
    'UNEMPLOYED':   3
    'NON-WORKER':   4

# Map travel party composition label to code
COMPOSITION:
    'ALL_ADULTS':    1
    'ALL_CHILDREN':  2
    'MIXED':         3

JOINT_CAT:
    'NOT-JOINT':     0
    'JOINT':         1
    'JOINT-GROUPED': 2

JOINT_TOUR_CAT:
    'INDEPENDENT':   1
    'PART_JOINT':    2
    'FULL_JOINT':    3
    'PROB_JOINT':    4

FACILITY:
    'Interstate': 1
    'Principal Arterial': 3
    'Minor Arterial': 4
    'Major Collector': 5
    'Minor Collector': 6
    'Local Road': 7
    'Ramp': 30
    
MTF:
    '1 Work': 1
    '2 Work': 2
    '1 School': 3
    '2 School': 4
    '1 Work & 1 School': 5
    
OCC_TYPE:
    'Management': 1
    'Service': 2
    'Sales & Office': 3
    'Natural Resources': 4
    'Production': 5
    'Military': 6
    'Total': 7

AGE_BINS:
    '0-5': 0        #1
    '5-15': 5       #2
    '15-7': 15      #3
    '17-24': 17     #4
    '24-34': 24     #5
    '34-44': 34     #6
    '44-49': 44     #7
    '49-54': 49     #8
    '54-59': 54     #9
    '59-64': 59     #10
    '64-74': 64     #11
    '74-79': 74     #12
    '79-84': 79     #13
    '84-999': 84    #14

