# Declare the custom processing steps to run here
START_FROM: SPAToolModule
PROCESSING_STEPS:
    GetAccessDBData:
        module: accessdb
        output_dir: raw
        data:
            database:
                file: 'RP_2014_141218.accdb'
                read_csv: False
        configs:
            dictionary_file: dbdata_specs/codebook_dictionary.csv
            categories_file: dbdata_specs/codebook_categories.csv
    ExpressionPreProcess:
        #        skip: True
        module: expressions
        from_pipeline: False # Read directly from pipeline, or pull from directory
        output_dir: preprocessed
        data:
            household:
                file: raw/household.csv
                index: household_id
            person:
                file: raw/person.csv
                index: person_id
            trip:
                file: raw/trip.csv
                index: trip_id
            day:
                file: raw/day.csv
                index: day_id
            vehicle:
                file: raw/vehicle.csv
                index: vehicle_id
            car_salikgates:
                file: raw/car_salikgates.csv
                index: car_salikgates_id
            trip_hhcompanions_pnum:
                file: raw/trip_hhcompanions_pnum.csv
                index: trip_hhcompanions_pnum_id
            zone:
                file: raw/zone.csv
                index: zone_id
        configs:
            mapping_file: preprocess_specs/preprocess_mapping.csv
            long_expressions: preprocess_specs/long_expressions.py # Can define more complex functions to run in a python file.
    TripsToPlace:
        module: trips_to_place
        from_pipeline: False # Read directly from pipeline, or pull from directory
        output_dir: preprocessed
        data:
            household:
                file: preprocessed/household.csv
                index: household_id
            person:
                file: preprocessed/person.csv
                index: person_id
            trip:
                file: preprocessed/trip.csv
                index: trip_id

    SPAToolModule:
        module: legacy_spa
        from_pipeline: False
        output_dir: final_data
        data:
            household:
                file: preprocessed/household.csv
                index: household_id
            person:
                file: preprocessed/person.csv
                index: person_id
            trip:
                file: preprocessed/trip.csv
                index: trip_id
            place:
                file: preprocessed/place.csv
                index: place_id
        configs:
            # These are variable key mappings for the variables aggregated in the SPA tool.
            spa_mapping:  spa_specs/variable_mapping.yaml
             
            
