# Declare the custom processing steps to run here
PROCESSING_STEPS:
    GetDBData:
        module: accessdb
        dictionary_file: preprocess_codebook_dictionary.csv
        categories_file: preprocess_codebook_categories.csv
        database_file: 'C:\\Users\\nick.fournier\\Resource Systems Group, Inc\\Model Development - Dubai RTA ABM Development Project\\data\\fromIBI/2014 Survey Data\\2014-12-20_SP_RP_Data_Aur\\RP_2014_141218.accdb'
        output_name: raw_data
    ExpressionPreProcess:
        module: expressions
        mapping_file: preprocess_mapping.csv
        output_name: preprocessed_data
    LegacySPA:
        module: legacy_spa
        output_name: final_data
        # LegacySPA Constants
        IN_DIR: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/new/"
        OUT_DIR_PATH: "E:/Projects/Clients/sandag/TO21_Recalibration/SANDAG_Data_Proc/processed/output/"
        COMPUTE_TRIP_DIST: True     #true if trip distance is to be computed from route file
        NEGLIGIBLE_DELTA_TIME: 10   #time stamps within this margin of difference can be considered as identical 
        MAX_VOLUNTEER_MINUTES: 120  #work duration le this value is considered volunteer work 
        MAX_XFERS: 3                #number of place holders for transit transfers in the output trip file
        START_OF_DAY_MIN: 180       #3:00am
        TIME_WINDOW_BIN_MIN: 30     #bin width in minutes
        WORK_LOCATION_BUFFER: 0.25  # distance buffer to check if activity location is primary work location
        INDEX_JTRIP_BY_DEPTIME: 0   #1 if index by trip departure time at origin, 0 if by trip arrival time at destination
        SurveyChangeModeCode: 7
        SurveyHomeCode: [1,2]
        SURVEY_DO_PURP_CODE: 8
        SURVEY_PU_PURP_CODE: 9
        SurveySchoolPurp: [5,6]
        SurveyWorkPurp: [3,4]
        SurveyWorkRelatedPurp: 11