# Declare the custom processing steps to run here
START_FROM: ExpressionPreProcess

PROCESSING_STEPS:
    ReadMSAccessDB:
        module: database.msaccessdb
        output_dir: raw
        data:
            database:
                file: 'RP_2014_141218.accdb'
                read_csv: False
        configs:
            dictionary_file: db_specs/codebook_dictionary.csv
            categories_file: db_specs/codebook_categories.csv

    ExpressionPreProcess:
        #        skip: True
        module: expressions.expressions_module
        from_pipeline: False # Read directly from pipeline, or pull from directory
        output_dir: preprocessed
        data:
            household:
                file: raw/household.csv
                index: household_id
            person:
                file: raw/person.csv
                index: person_id
            trip:
                file: raw/trip.csv
                index: trip_id
            day:
                file: raw/day.csv
                index: day_id
            vehicle:
                file: raw/vehicle.csv
                index: vehicle_id
            car_salikgates:
                file: raw/car_salikgates.csv
                index: car_salikgates_id
            trip_hhcompanions_pnum:
                file: raw/trip_hhcompanions_pnum.csv
                index: trip_hhcompanions_pnum_id
            zone:
                file: raw/zone.csv
                index: zone_id
        configs:
            mapping_file: preprocess_specs/preprocess_mapping.csv

    TripsToPlace:
        module: placemaking.trip_to_place
        from_pipeline: False # Read directly from pipeline, or pull from directory
        output_dir: preprocessed
        data:
            household:
                file: preprocessed/household.csv
                index: household_id
            person:
                file: preprocessed/person.csv
                index: person_id
            trip:
                file: preprocessed/trip.csv
                index: trip_id

    SPAToolModule:
        module: legacy_spa.spa_module
        from_pipeline: False
        output_dir: spa_output
        data:
            household:
                file: preprocessed/household.csv
                index: household_id
            person:
                file: preprocessed/person.csv
                index: person_id
            trip:
                file: preprocessed/trip.csv
                index: trip_id
            place:
                file: preprocessed/place.csv
                index: place_id
#        configs:
            # These are variable key mappings for the variables aggregated in the SPA tool.
#            spa_mapping:  spa_specs/variable_mapping.yaml
             
    Visualizer:
        skip: True
        module: visualizer.visualizer_module
        from_pipeline: False
        output_dir: visualizer
        data:
            base:
                zones:
                    file: raw/zone.csv
                    index: zone_id
                pre_person:
                    file: preprocessed/person.csv
                    index: person_id
                pre_place:
                    file: preprocessed/place.csv
                    index: place_id
                spa_household: spa_output/households.csv
                spa_person: spa_output/persons.csv
                spa_trips: spa_output/trips.csv
                spa_tours: spa_output/tours.csv
                spa_jultrips: spa_output/unique_joint_ultrips.csv
                spa_jtours: spa_output/unique_joint_tours.csv
            build:
                zones:
                    file: raw/zone.csv
                    index: zone_id
                preprocessed:
                    pre_place:
                        file: preprocessed/place.csv
                        index: place_id
                spa_output:
                    spa_household: spa_output/households.csv
                    spa_person: spa_output/persons.csv
                    spa_trips: spa_output/trips.csv
                    spa_tours: spa_output/tours.csv
                    spa_jultrips: spa_output/unique_joint_ultrips.csv
                    spa_jtours: spa_output/unique_joint_tours.csv
        configs:
            parameters:  visualizer_specs/parameters.yaml