# Declare the custom processing steps to run here
START_FROM: LegacySPA
PROCESSING_STEPS:
    GetDBData:
        module: accessdb
        dictionary_file: preprocess_specs/codebook_dictionary.csv
        categories_file: preprocess_specs/codebook_categories.csv
        database_file: 'RP_2014_141218.accdb'
        output_name: raw
#        skip: True
#    TripsToPlace:
#        module: trips_to_place
#        data_directory: 'raw'
#        from_pipeline: False # Read directly from pipeline, or pull from directory
#        dest_zone_col: dest_zone_id
#        output_name: preprocessed
#        skip: False
    ExpressionPreProcess:
        module: expressions
        mapping_file: preprocess_specs/preprocess_mapping.csv
        long_expressions: preprocess_specs/long_expressions.py # Can define more complex functions to run in a python file.
        data_directory: 'raw'
        # tables:   # can specify this, or else all files will be loaded from folder
         # - person
         # - household
        from_pipeline: False # Read directly from pipeline, or pull from directory
        output_name: preprocessed
#        skip: True
    LegacySPA:
        module: legacy_spa
        data_directory: preprocessed
        from_pipeline: False
        output_name: final_data
        specs:
            # These are variable key mappings for the variables aggregated in the SPA tool.
            trip_columns: spa_specs/trip_columns.csv
            tour_columns: spa_specs/tour_columns.csv
            spa_mapping:  spa_specs/variable_mapping.yaml
             
            
