# Visualizer settings
# TODO cleanup redundancies

Key: Value
BASE_SCENARIO_NAME: Survey
BUILD_SCENARIO_NAME: Model
BASE_SAMPLE_RATE: 1.0
BUILD_SAMPLE_RATE: 1.000
MAX_ITER: 1
OUTPUT_HTML_NAME: dubai_visualizer.html
R_LIBRARY: C:\projects\metc-asim-model\Visualizer\contrib\RPKG
# FULL_HTML_NAME: MetCouncil_visualizer
# CT_ZERO_AUTO_FILE_NAME: ct_zero_auto.shp
IS_BASE_SURVEY: Yes
# VIS_ABM_INPUTS: C:\projects\metc-asim-model\activitysim\data
# VIS_SKIMS_DIR: C:\projects\metc-asim-model\activitysim\data
# VIS_ABM_DIR: C:\projects\metc-asim-model\activitysim\output
# VIS_ABM_SUMMARIES_DIR: C:\projects\metc-asim-model\Visualizer\data\calibration_runs\summarized
# VIS_ZONE_DIR: C:\projects\metc-asim-model\Visualizer/data/SHP
VIS_BASE_DATA_DIR: data\visualizer\summaries
VIS_BUILD_DATA_DIR: data\visualizer\summaries
# VIS_ZONE_FILE: TAZ2010.shp
VIS_DIR: data\visualizer
# CENSUS_DATA_PATH: C:\projects\metc-asim-model\Visualizer/data/census
# ASSIGNED: 1


SUMMARIES:
    - activePertypeDistbn
    - autoOwnership
    - avgStopOutofDirectionDist_vis
    - dapSummary_vis
    - hhSizeDist
    # hhsizeJoint
    # inmSummary_vis
    # jointComp
    # jointCompPartySize
    # jointPartySize
    # jointToursHHSize
    # jtf
    # mtfSummary_vis
    # pertypeDistbn
    # stopDC_vis
    # stopfreqDir_vis
    # stoppurpose_tourpurpose_vis
    # stopTripDep_vis
    # todProfile_vis
    # totals
    # total_tours_by_pertype_vis
    # trips_flow

